repos:
  - repo: local
    hooks:
      - id: golangci-lint
        pass_filenames: false
        name: golangci-lint
        entry: golangci-lint run
        language: system
        types: [go]

  - repo: local
    hooks:
      - id: gosec
        pass_filenames: false
        name: gosec
        entry: gosec ./...
        language: system
        types: [go]
        args: ["-exclude-dir=vendor,examples,tests"]

  - repo: local
    hooks:
      - id: govulncheck
        pass_filenames: false
        name: govulncheck
        entry: govulncheck ./...
        language: system
        types: [go]

  - repo: local
    hooks:
      - id: go-test
        pass_filenames: false
        name: go test
        entry: go test ./...
        language: system
        types: [go]